### ISSUE TITLE
Request: Save .conf file to the folder of the file - not MPV

### ISSUE THREAD

**Issue by Zefferis** [Static39/mpv-scripts#2] opened 2022-07-12 03:34 UTC
OS: Windows 10

Issue:
A behavior I've noticed is that the .conf file appears to save in the directory in which MPV is opened.

This doesn't behave well with other scripts like ``file-browser`` that allow MPV users to open files from other directories.

In my use case I start MPV and use the file-browser to play files I'm interest in.  The osc.lua in this case puts the .conf file in my home directory,  where I started MPV, and doesn't place itself in the directory I'm playing the videos from.
__
Request:
Is it possible to have the osc.conf place the .conf file in the directory that the file is played from - and read the directory the file is played from for an existing .conf file?

**Comment by Static39** [comment] 2022-07-12 03:49
I can see where that would cause issues. I always open files the same way so opening files within MPV didn't occur to me. I'll look into it tonight and hopefully have it fixed by tomorrow since it seems like an easy fix.

**Comment by Static39** [comment] 2022-07-12 06:59
The script now writes/reads the .conf file from the directory of the currently playing media file now instead of the MPV working directory. I tested with `file-browser` and didn't encounter any issues. If you use the updated script you shouldn't have any issues now.

**Comment by Zefferis** [comment] 2022-07-12 19:37
Hey @Static39 ! Thank you this update -

I've noticed that when using something like file-browser, it behaves as expected for the first file played:

1) Its adding the .conf file to the directory of the current playing media file*
2) Its reading the .conf file if it exists already in the directory of the current file

However;

When playing a different file from a different directory (when using file-browser) it does not re-check if there is an existing .conf file in the new directory
If there is no existing .conf file, it uses the settings of the previous .conf from the previous directory. (not preferred)

__
Request:
If MPV plays a media file from a different directory (or any new file) osc.lua should check if there is an existing .conf , if there is no existing .conf in the media directory, it should use media file default preferences or mpv settings.
__

osc.lua already appears to work flawlessly if you move from one directory that has a .conf to another directory that has a .conf 👍 

:) Thank you so much for making the initial edit, do you have a place for donations?

**Comment by Static39** [comment] 2022-07-13 00:18
I was able to reproduce the issue and am currently working on a fix. I believe the issue is due to `file-browser` carrying over current media settings when changing media files which I assume is intentional behavior.
However, in this use case it causes issues so I'm working on way to restore default/config properties on file load.

PS: I don't have donations set up, but I very much appreciate the feedback :)

**Comment by Static39** [comment] 2022-07-13 08:37
After messing around with MPV and `file-browser` for awhile I've come to the conclusion that this is more of an "issue" with `file-browser` than with this script.

When `file-browser` loads a new media file it doesn't load the default/config MPV properties and instead uses the current media properties such as sub-scale, sub-pos, etc. which I assume is intentional behavior.
This is something that could technically be patched on this script, but it could overwrite potentially desirable behavior.

> If MPV plays a media file from a different directory (or any new file) osc.lua should check if there is an existing .conf , if there is no existing .conf in the media directory, it should use media file default preferences or mpv settings.

Essentially, the script already has this behavior but `file-browser` persists current properties.
This is something that makes more sense to add as a optional feature of `file-browser` than to attempt to patch on this script since the undesirable behavior in question is technically on the side of `file-browser`.

However, I plan on restructuring some of the script settings into a config file and once I do that I can add a compatibility option for `file-browser` like scripts.

**Comment by Zefferis** [comment] 2022-07-13 18:11
Thank you so much for looking into this @Static39 !

Let me know if you open up a donation portal 👍

**Closed as completed** 2022-07-14 02:44 UTC
